config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  # pos
  namespace :pos do
    root to:'home#index'
    resources :orders, except: [:show, :destroy]
    resources :returns, except: [:show, :destroy]
  end

  # shop
  namespace :shop do
    root to:'home#index'
    resources :stores, only:[:index, :show]
    resources :products, only:[:index, :show]
    resources :variants, only:[:index, :show]
  end

  # mall
  namespace :mall do
    resources :stores
    resources :catalogs

    # resources :products
    # resources :variants
    # resources :addresses
    # resources :payment_methods
    # resources :payments
    # resources :shipping_methods
    # resources :shipments

    root to: 'home#index'
  end

  # survey
  namespace :survey do
    resources :forms, except: [:show] do
      resources :fields, except: [:show]
      resources :records, only: [:new, :create, :destroy, :index]
    end
  end

  # forum
  namespace :forum do
    resources :tags do
      collection do
        get 'latest'
      end
    end

    resources :articles do
      collection do
        get 'latest'
      end
    end

    resources :comments, except: [:show] do
      collection do
        get 'latest'
      end
    end

  end

  # admin
  namespace :admin do
    %w(info languages nav donate).each do |act|
      get "site/#{act}"
      post "site/#{act}"
    end

    get 'site/status'

    resources :users, only: [:index] do
      member do
        post 'apply'
        post 'deny'
      end
    end

    resources :cards, except: [:show]
  end

  post '/votes' => 'votes#index'

  resources :attachments, only: [:index, :new, :create, :destroy]

  # leave words
  resources :leave_words, except: [:edit, :update, :show]

  # seo
  get '/robots' => 'home#robots', constraints: {format: 'txt'}
  get '/rss' => 'home#rss', constraints: {format: 'atom'}

  # home
  post '/search' => 'home#search'
  %w(dashboard donate).each {|act|get "/#{act}" => "home##{act}"}


  # third
  devise_for :users

  authenticate :user, lambda {|u| u.is_admin?} do
    mount Sidekiq::Web => '/jobs'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/views/shared/_flash.html.erb
<% if notice %>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong><%= notice %></strong>
    </div>
<% end %>

<% if alert %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong><%= alert %></strong>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<hr/>
<footer>
  <p class="float-right">
    <%= t '.all_languages' %>:
    <% Setting.languages.each do |k, v| %>
        <%= link_to v, root_path(locale: k), target: :_blank %>
    <% end %>
  </p>
  <p>
    &copy; <%= site_info :copyright %>
    <% links = Setting["#{locale}.nav.footer"] %>
    <% if links %>
        <% links.each do |l| %>
            &middot; <%= link_to l.fetch('label'), l.fetch('href'), target: :_blank %>
        <% end %>
    <% end %>
  </p>
</footer>

app/views/shared/_header.html.erb
<% links = Setting["#{locale}.nav.header"] %>
<nav class="navbar navbar-expand-lg navbar-inverse fixed-top bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to  site_info(:sub_title), root_path, class: 'navbar-brand' %>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <% if links %>
          <% links.each_with_index do |d, i| %>
              <% id = "header-dropdown-#{i+1}" %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="<%= id %>" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= d['label'] %></a>
                <div class="dropdown-menu" aria-labelledby="<%= id %>">
                  <% d.fetch('items').each do |l| %>
                      <%= link_to l.fetch('label'), l.fetch('href'), class: 'dropdown-item' %>
                  <% end %>
                </div>
              </li>
          <% end %>
      <% end %>

      <%= render 'shared/personal_bar' %>

    </ul>
    <%= render 'shared/search_form' %>
  </div>
</nav>

app/views/shared/_personal-bar.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" id="personal-bar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= user_signed_in? ? t('.welcome', name: current_user.name) : t('.sign-in-or-up') %>
  </a>
  <div class="dropdown-menu" aria-labelledby="personal-bar">
    <% links = user_signed_in? ?
                   [
                       {label: '.profile', href: edit_user_registration_path},
                       {label: 'home.dashboard.title', href: dashboard_path},
                       {label: 'devise.invitations.new.header', href: new_user_invitation_path},
                   ] :
                   [
                       {label: 'devise.shared.links.sign_in', href: new_user_session_path},
                       {label: 'devise.shared.links.sign_up', href: new_user_registration_path},
                       {label: 'devise.shared.links.forgot_your_password', href: new_user_password_path},
                       {label: 'devise.shared.links.didn_t_receive_confirmation_instructions', href: new_user_confirmation_path},
                       {label: 'devise.shared.links.didn_t_receive_unlock_instructions', href: new_user_unlock_path},
                       {label: 'leave_words.new.title', href: new_leave_word_path},
                   ] %>
    <% links.each do |l| %>
        <%= link_to t(l.fetch :label), l.fetch(:href), class: 'dropdown-item' %>
    <% end %>

    <% if user_signed_in? %>
        <div class="dropdown-divider"></div>
        <%= link_to t('.sign-out'), destroy_user_session_path, class: 'dropdown-item', data: {confirm: t('devise.registrations.edit.are_you_sure')}, method: :delete %>
    <% end %>
  </div>
</li>

app/views/shared/_personal_bar.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="personal-bar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= user_signed_in? ? t('.welcome', name: current_user.name) : t('.sign_in_or_up') %>
  </a>
  <div class="dropdown-menu" aria-labelledby="personal-bar">
    <% links = user_signed_in? ?
                   [
                       {label: '.profile', href: edit_user_registration_path},
                       {label: 'home.dashboard.title', href: dashboard_path},
                       {label: 'devise.invitations.new.header', href: new_user_invitation_path},
                   ] :
                   [
                       {label: 'devise.shared.links.sign_in', href: new_user_session_path},
                       {label: 'devise.shared.links.sign_up', href: new_user_registration_path},
                       {label: 'devise.shared.links.forgot_your_password', href: new_user_password_path},
                       {label: 'devise.shared.links.didn_t_receive_confirmation_instructions', href: new_user_confirmation_path},
                       {label: 'devise.shared.links.didn_t_receive_unlock_instructions', href: new_user_unlock_path},
                       {label: 'leave_words.new.title', href: new_leave_word_path},
                   ] %>
    <% links.each do |l| %>
        <%= link_to t(l.fetch :label), l.fetch(:href), class: 'dropdown-item' %>
    <% end %>

    <% if user_signed_in? %>
        <div class="dropdown-divider"></div>
        <%= link_to t('.sign_out'), destroy_user_session_path, class: 'dropdown-item', data: {confirm: t('devise.registrations.edit.are_you_sure')}, method: :delete %>
    <% end %>
  </div>
</li>

app/views/shared/_search-form.html.erb
<%= form_tag search_path, method: :post, class: 'form-inline mt-2 mt-md-0' do %>
    <%= text_field_tag :keywords, nil, class: 'form-control mr-sm-2' %>
    <%= submit_tag t('.submit'), class: 'btn btn-outline-success my-2 my-sm-0' %>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_tag search_path, method: :post, class: 'form-inline mt-2 mt-md-0' do %>
    <%= text_field_tag :keywords, nil, class: 'form-control mr-sm-2' %>
    <%= submit_tag t('.submit'), class: 'btn btn-outline-success my-2 my-sm-0' %>
<% end %>

app/views/shared/_vote.html.erb
<p>
  <% {up:1, down:-1}.each do |k, v|%>
      <%= link_to image_tag(asset_path("#{k}.png"), class: 'vote'), votes_path(rty: rty, rid: rid, mark: v), method: :post %>
  <%end%>
</p>