config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  # pos
  namespace :pos do
    root to:'home#index'
    resources :orders, except: [:show, :destroy]
    resources :returns, except: [:show, :destroy]
  end

  # shop
  namespace :shop do
    root to:'home#index'
    resources :stores, only:[:index, :show]
    resources :products, only:[:index, :show]
    resources :variants, only:[:index, :show]
  end

  # mall
  namespace :mall do
    resources :stores
    resources :catalogs

    # resources :products
    # resources :variants
    # resources :addresses
    # resources :payment_methods
    # resources :payments
    # resources :shipping_methods
    # resources :shipments

    root to: 'home#index'
  end

  # survey
  namespace :survey do
    resources :forms, except: [:show] do
      resources :fields, except: [:show]
      resources :records, only: [:new, :create, :destroy, :index]
    end
  end

  # forum
  namespace :forum do
    resources :tags do
      collection do
        get 'latest'
      end
    end

    resources :articles do
      collection do
        get 'latest'
      end
    end

    resources :comments, except: [:show] do
      collection do
        get 'latest'
      end
    end

  end

  # admin
  namespace :admin do
    %w(info languages nav donate).each do |act|
      get "site/#{act}"
      post "site/#{act}"
    end

    get 'site/status'

    resources :users, only: [:index] do
      member do
        post 'apply'
        post 'deny'
      end
    end

    resources :cards, except: [:show]
  end

  post '/votes' => 'votes#index'

  resources :attachments, only: [:index, :new, :create, :destroy]

  # leave words
  resources :leave_words, except: [:edit, :update, :show]

  # seo
  get '/robots' => 'home#robots', constraints: {format: 'txt'}
  get '/rss' => 'home#rss', constraints: {format: 'atom'}

  # home
  post '/search' => 'home#search'
  %w(dashboard donate).each {|act|get "/#{act}" => "home##{act}"}


  # third
  devise_for :users

  authenticate :user, lambda {|u| u.is_admin?} do
    mount Sidekiq::Web => '/jobs'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  validates :title, :content_type, presence: true
  mount_uploader :avatar, AvatarUploader
  belongs_to :user

  def read(file)
    self.title = file.original_filename
    self.content_type =file.content_type
    self.avatar = file
  end

  def is_picture?
    self.content_type.start_with?('image/')
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def index
    authorize Attachment

    if current_user.is_admin?
      @attachments = Attachment.all.order(updated_at: :desc)
    else
      @attachments = Attachment.where(user_id: current_user.id).order(updated_at: :desc)
    end
  end

  def create
    authorize Attachment

    @attachment = Attachment.new user_id: current_user.id
    @attachment.read params.fetch(:file)

    if @attachment.save
      redirect_to attachments_path
    else
      render 'new'
    end
  end


  def destroy
    @attachment = Attachment.find(params[:id])
    authorize @attachment
    @attachment.destroy

    redirect_to attachments_path
  end


end

app/views/attachments/index.html.erb
<h2><%= title t('.title')%></h2>
<hr/>

<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th><%= t 'attributes.updated_at'%></th>
    <th><%= t 'attributes.title'%></th>
    <th>
      <%= t 'buttons.manage'%>
      <%= link_to t('buttons.new'), new_attachment_path, class: 'btn btn-sm btn-link'%>
    </th>
  </tr>
  </thead>
  <tbody>
  <% @attachments.each do |it| %>
      <tr>
        <td><%= time_ago_in_words it.updated_at %></td>
        <td>
          <% if it.is_picture? %>
            <%= link_to it.title, it.avatar.landscape.url, target: :_blank %>
            <br/>
            <%= link_to image_tag(it.avatar.thumb.url), it.avatar.thumb.url, target: :_blank %>
            <%= link_to image_tag(it.avatar.small.url), it.avatar.small.url, target: :_blank %>
          <% else %>
            <%= link_to it.title, it.avatar.url %>
          <%end%>
        </td>
        <td>
          <div class="btn-group btn-group-sm">
            <%= link_to t('buttons.delete'), attachment_path(it), data: {confirm: t('messages.are_you_sure')}, method: :delete, class: 'btn btn-danger' %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/attachments/new.html.erb
<h2><%= title t('.title')%></h2>
<hr/>
<%= form_tag attachments_path, multipart: true do %>
    <div class="form-group">
      <%= file_field_tag :file, class:'form-control-file' %>
    </div>
    <%= submit_tag t('buttons.submit'), class: 'btn btn-primary' %>
<%end%>