config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  # pos
  namespace :pos do
    root to:'home#index'
    resources :orders, except: [:show, :destroy]
    resources :returns, except: [:show, :destroy]
  end

  # shop
  namespace :shop do
    root to:'home#index'
    resources :stores, only:[:index, :show]
    resources :products, only:[:index, :show]
    resources :variants, only:[:index, :show]
  end

  # mall
  namespace :mall do
    resources :stores
    resources :catalogs

    # resources :products
    # resources :variants
    # resources :addresses
    # resources :payment_methods
    # resources :payments
    # resources :shipping_methods
    # resources :shipments

    root to: 'home#index'
  end

  # survey
  namespace :survey do
    resources :forms, except: [:show] do
      resources :fields, except: [:show]
      resources :records, only: [:new, :create, :destroy, :index]
    end
  end

  # forum
  namespace :forum do
    resources :tags do
      collection do
        get 'latest'
      end
    end

    resources :articles do
      collection do
        get 'latest'
      end
    end

    resources :comments, except: [:show] do
      collection do
        get 'latest'
      end
    end

  end

  # admin
  namespace :admin do
    %w(info languages nav donate).each do |act|
      get "site/#{act}"
      post "site/#{act}"
    end

    get 'site/status'

    resources :users, only: [:index] do
      member do
        post 'apply'
        post 'deny'
      end
    end

    resources :cards, except: [:show]
  end

  post '/votes' => 'votes#index'

  resources :attachments, only: [:index, :new, :create, :destroy]

  # leave words
  resources :leave_words, except: [:edit, :update, :show]

  # seo
  get '/robots' => 'home#robots', constraints: {format: 'txt'}
  get '/rss' => 'home#rss', constraints: {format: 'atom'}

  # home
  post '/search' => 'home#search'
  %w(dashboard donate).each {|act|get "/#{act}" => "home##{act}"}


  # third
  devise_for :users

  authenticate :user, lambda {|u| u.is_admin?} do
    mount Sidekiq::Web => '/jobs'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/leave_word.rb
class LeaveWord < ApplicationRecord
  validates :body, presence: true


  before_create :set_created_at

  private
  def set_created_at
    self.created_at = Time.now
  end
end

app/controllers/leave_words_controller.rb
class LeaveWordsController < ApplicationController
  before_action :require_admin!, only: [:index, :destroy]

  def index
    @leave_words = LeaveWord.all
  end

  def new
    @leave_word = LeaveWord.new
    authorize @leave_word
  end

  def create
    @leave_word = LeaveWord.new params.require(:leave_word).permit(:body)

    if @leave_word.save
      flash[:notice] = t 'messages.success'
      redirect_to new_leave_word_path
    else
      render 'new'
    end
  end

  def destroy
    @leave_word = LeaveWord.find params.fetch(:id)
    @leave_word.destroy
    redirect_to leave_words_path
  end


  private
  def require_admin!
    authorize :dashboard, :admin?
  end
end

app/views/leave_words/index.html.erb
<h2><%= title t('.title')%></h2>
<hr/>

<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th><%= t 'attributes.created_at'%></th>
    <th><%= t 'attributes.body'%></th>
    <th><%= t 'buttons.manage'%></th>
  </tr>
  </thead>
  <tbody>
  <% @leave_words.each do |it| %>
    <tr>
      <th scope="row"><%= time_ago_in_words it.created_at%></th>
      <td><pre><%= it.body%></pre></td>
      <td>
        <%= link_to t('buttons.delete'), leave_word_path(it), data: {confirm: t('messages.are_you_sure')}, method: :delete, class: 'btn btn-sm btn-danger' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/leave_words/new.html.erb
<h2><%= title t('.title') %></h2>
<hr/>
<%= simple_form_for @leave_word do |f| %>
    <%= f.input :body, as: :text, autofocus: true, input_html: {rows: 6}, hint: t('.hint') %>
    <%= f.button :submit, t('buttons.submit') %>
<% end %>